---
#- name: "Ver gather"
#  debug:
#    var: ansible_facts
#- name: "Obtener hostnames"
#  ansible.builtin.import_tasks:
#      file: hostname.yml
#- name: "Memoria"
#  ansible.builtin.import_tasks:
#      file: memoria.yml
#- name: "red_ip"
#  ansible.builtin.import_tasks:
#      file: red_ip.yml
# - name: "Dates"
#   ansible.builtin.import_tasks:
#       file: date_time.yml
# - name: "cpus"
#   ansible.builtin.import_tasks:
#       file: cpu.yml
# - name: "uptime"
#   ansible.builtin.import_tasks:
#       file: uptime.yml
#- name: "ips"
#  ansible.builtin.import_tasks:
#      file: ips.yml
- name: "dev_ips"
  ansible.builtin.import_tasks:
      file: dev_ips.yml

