- name: "Inicializar variable STNMAP"
  ansible.builtin.set_fact:
    STNMAP: 'No'
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Print the package facts"
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: "Chequear si existe el paquete nmap"
  ansible.builtin.set_fact:
        STNMAP: 'Yes'
  when: "'nmap' in ansible_facts.packages"