- name: "Comprobar si existe una linea que empiece con la IP del servidor en /etc/hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ipadresses }}'
    line: '/#{{ ipadresses }}'
  check_mode: True
  register: salida
  no_log: true
- name: "Actualizar variable EHOST"
  set_fact:
    EHOST: 'IPonHOSTS_OK'
  when: salida.msg == 'line replaced'
  no_log: true