- name: "IP 1"
  debug:
    msg: "La direccion ip 1 es : {{ ansible_facts['all_ipv4_addresses'][0] }}"
- name: "IP 2"
  debug:
    msg: "La direccion ip 2 es : {{ ansible_facts['all_ipv4_addresses'][1] }}"
  when: ansible_facts['all_ipv4_addresses'][1] is defined
- name: "IP 3"
  debug:
    msg: "La direccion ip 3 es : {{ ansible_facts['all_ipv4_addresses'][2] }}"
  when: ansible_facts['all_ipv4_addresses'][2] is defined
# - name: "Todas las IP"
#   debug:
#     msg: "La direcion IP es {{ item }}"
#   loop: "{{ ansible_facts['all_ipv4_addresses'] }}"

- name: "Inicializar variable a IPonHOSTS_NOK"
  set_fact:
    EHOST: 'IPonHOSTS_NOK'
  no_log: true
- name: "Llamada a proceso red_ip_ehosts"
  ansible.builtin.include_tasks:
    file: red_ip_ehosts.yml
  vars:
    ipadresses: "{{ item }}"
  loop: "{{ ansible_facts['all_ipv4_addresses'] }}"
  no_log: true

- name: "Visualizar valor EHOST"
  ansible.builtin.debug:
    var: EHOST