- name: "Inicializar variable STNMAP"
  ansible.builtin.set_fact:
    STTCPD: 'No'
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Print the package facts"
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: "Chequear si existe el paquete tcpdump"
  ansible.builtin.set_fact:
        STTCPD: 'Yes'
  when: "'tcpdump' in ansible_facts.packages"

- name: "Visualizar contenido de STTCPD"
  ansible.builtin.debug:
    msg: " El valor de STTCPD es {{ STTCPD}}"