- name: "Ver puntos de montaje"
  debug:
    var: ansible_facts['mounts']
- name: "Ver nombres de los puntos de montaje"
  debug:
    msg: "Punto de montaje de boot esssssssssssssssssssssssssssssss  {{ item.mount }}"
  loop: "{{ ansible_mounts }}"
  when: item.mount == '/boot'
- name: "Capturar todos los datos de los vgs en vgslist"
  ansible.builtin.set_fact:
    vgslist: ""
- name: "Ver vgs"
  debug:
    msg: "El nombre del vg es {{ item.key }} y el tamaño es {{ item.value.size_g }}"
  loop: "{{ ansible_lvm.vgs | dict2items }}"

- name: "Agregar valores a vgslist"
  ansible.builtin.set_fact:
    vgslist: "{{ vgslist }} {{ item.key }},{{ item.value.size_g }};" 
  loop: "{{ ansible_lvm.vgs | dict2items }}"

- name: "Ver puntos de montaje"
  debug:
    var: vgslist 